#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    SELECT 'CREATE DATABASE trickcal_bot OWNER "${POSTGRES_USER}"'
    WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'trickcal_bot')\gexec
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "trickcal_bot" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS bot AUTHORIZATION ${POSTGRES_USER};
    ALTER DATABASE trickcal_bot SET search_path TO bot, public;

    GRANT ALL ON SCHEMA bot TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA bot TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA bot TO ${POSTGRES_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA bot
    GRANT ALL ON TABLES TO ${POSTGRES_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA bot
    GRANT ALL ON SEQUENCES TO ${POSTGRES_USER};
EOSQL
